'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EducationTypeLookup

    '''<summary>
    '''odsEducationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsEducationType As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''upMainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upMainContent As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''valCannotDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valCannotDelete As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''gvEducatuionType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvEducatuionType As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''vsEditEducationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsEditEducationType As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''vsAddEducationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsAddEducationType As Global.System.Web.UI.WebControls.ValidationSummary
End Class
