'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManageGeneral

    '''<summary>
    '''odsCountries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsCountries As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsProvinceState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsProvinceState As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsEducationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsEducationType As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''ddlCountries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCountries As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rblCountries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblCountries As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''upCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upCountry As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCountry As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCountry As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''btnSaveCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveCountry As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''vsCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsCountry As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''upCountriesLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upCountriesLabel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblCountries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCountries As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlProvinceState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProvinceState As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rblProvinceState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblProvinceState As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''upProvinceState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upProvinceState As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtProvinceState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProvinceState As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvProvinceState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvProvinceState As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''btnSaveProvinceState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveProvinceState As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''vsProvinceState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsProvinceState As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''upProvinceStateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upProvinceStateLabel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblConProvinceState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConProvinceState As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''upMainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upMainContent As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''gvEducatuionType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvEducatuionType As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''vsEditEducationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsEditEducationType As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''vsAddEducationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsAddEducationType As Global.System.Web.UI.WebControls.ValidationSummary
End Class
