'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProvinceStateLookup

    '''<summary>
    '''odsProvinceStateCA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsProvinceStateCA As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsProvinceStateUS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsProvinceStateUS As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''gvProvinceStateCA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvProvinceStateCA As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gvProvinceStateUS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvProvinceStateUS As Global.System.Web.UI.WebControls.GridView
End Class
