'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UpdateSemester

    '''<summary>
    '''captionSemester control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents captionSemester As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rblSemesters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblSemesters As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''captionSemesterEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents captionSemesterEndDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSemesterEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSemesterEndDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''calImg1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calImg1 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''RegularExpressionValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''btnUpdateSemester control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateSemester As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblSemesterUpdated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSemesterUpdated As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSemesterCantBeUpdated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSemesterCantBeUpdated As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''upAddNewUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upAddNewUsers As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''addNewUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addNewUsers As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UpdateProgressAddNewUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgressAddNewUsers As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''wizardAddUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wizardAddUsers As Global.System.Web.UI.WebControls.Wizard

    '''<summary>
    '''addUsersToSemester control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addUsersToSemester As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cblUsersToAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblUsersToAdd As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''addAllStudentsStep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addAllStudentsStep As Global.System.Web.UI.WebControls.WizardStep

    '''<summary>
    '''AddAllStudentsReportTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddAllStudentsReportTxt As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cbAllStudents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbAllStudents As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''addCoopAllStudentsStep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addCoopAllStudentsStep As Global.System.Web.UI.WebControls.WizardStep

    '''<summary>
    '''AddAllCoopStudentsReportTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddAllCoopStudentsReportTxt As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cbCoopStudents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbCoopStudents As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''addAllTeachersAndCoordinatorsStep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addAllTeachersAndCoordinatorsStep As Global.System.Web.UI.WebControls.WizardStep

    '''<summary>
    '''AddAllTeachersAndCoordinatorsReportTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddAllTeachersAndCoordinatorsReportTxt As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cbTeachersAndCoordinators control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbTeachersAndCoordinators As Global.System.Web.UI.WebControls.CheckBox
End Class
