//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAC.RACModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate : User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.RACAdvisorNotifications = new HashSet<RACNotification>();
        }
    
        public string Street { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public Nullable<int> PreferredMethodOfContact { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsArchived { get; set; }
        public bool IsPrivacyPolicyAccepted { get; set; }
        public System.DateTime DateRegistered { get; set; }
        public string RegistrationIP { get; set; }
    
        public virtual RACRequest RACRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RACNotification> RACAdvisorNotifications { get; set; }
        public virtual FinalizedRACContract FinalizedRACContract { get; set; }
    }
}
