//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAC.RACModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalizedRACContract
    {
        public int Id { get; set; }
        public byte[] Binary { get; set; }
        public string Name { get; set; }
        public System.DateTime DateUploaded { get; set; }
    
        public virtual Candidate Candidate { get; set; }
    }
}
