//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RacModelContainer : DbContext
    {
        public RacModelContainer()
            : base("name=RacModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RACRequest> RACRequest { get; set; }
        public virtual DbSet<UploadedDocument> UploadedDocument { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<Competency> Competencies { get; set; }
        public virtual DbSet<RACRequestCompetency> RACRequestCompetencies { get; set; }
        public virtual DbSet<RACRequestCompetencyElements> RACRequestCompetencyElements { get; set; }
        public virtual DbSet<CompetencyElement> CompetencyElement { get; set; }
        public virtual DbSet<CompetencyComment> RACRequestCompetencyComment { get; set; }
        public virtual DbSet<ValidationKey> ValidationKeys { get; set; }
        public virtual DbSet<FinalizedRACContracts> FinalizedRACContracts { get; set; }
        public virtual DbSet<RACAdvisorNotifications> RACAdvisorNotifications { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<CourseCompetency> CourseCompetencies { get; set; }
        public virtual DbSet<ElementMinistryData> ElementMinistryDatas { get; set; }
        public virtual DbSet<CompetencyMinistryData> CompetencyMinistryDatas { get; set; }
        public virtual DbSet<ProgramMinistryData> ProgramMinistryData { get; set; }
        public virtual DbSet<CourseMinistryData> CourseMinistryData { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public virtual DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public virtual DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public virtual DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public virtual DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
