//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSAdmin2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSAdmin2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        ///Update: Guillaume Mercier
        ///Date: 2018-May-05
        ///Changes: Added CES update
        ///
        ///always surround this entire script with a transaction rollback when debugging it:
        ///begin transaction
        ///	[code here]
        ///rollback transaction
        ///**/
        ///--begin transaction
        ///
        ///	set nocount on
        ///
        ///	declare @coordinatorRoleId int = (select top 1 IDRole from Applications.Role where Code = &apos;CO&apos;);
        ///	declare @currentSemesterYear smallint = (select top 1 [CurrentYearSemester] from [Applications].[Settings])
        ///	declare @rowsChanged int = 0;
        ///	
        ///	/* [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateCoordinatorScript {
            get {
                return ResourceManager.GetString("UpdateCoordinatorScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        ///Update: Guillaume Mercier
        ///Date: 2018-May-05
        ///Changes: Added CES update
        ///
        ///always surround this entire script with a transaction rollback when debugging it:
        ///begin transaction
        ///	[code here]
        ///rollback transaction
        ///**/
        ///--begin transaction
        ///
        ///	-- find the csadmin student role
        ///	declare @studentRoleId int;
        ///	select top(1) @studentRoleId = IDRole from Applications.Role where Code = &apos;ST&apos;
        ///
        ///
        ///	/*
        ///
        ///	declare @removedTeachers table(
        ///	IDUser int not null
        ///	)
        ///	insert into @removedTeachers (idUser)
        ///	select t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateStudentScript {
            get {
                return ResourceManager.GetString("UpdateStudentScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        ///Update: Guillaume Mercier
        ///Date: 2018-May-05
        ///Changes: Added CES update
        ///
        ///always surround this entire script with a transaction rollback when debugging it:
        ///begin transaction
        ///	[code here]
        ///rollback transaction
        ///**/
        ///
        ///
        ///--begin transaction
        ///
        ///	set nocount on
        ///
        ///	declare @teacherRoleId int = (select top 1 IDRole from Applications.Role where Code = &apos;TE&apos;);
        ///	declare @currentSemesterYear smallint = (select top 1 [CurrentYearSemester] from [Applications].[Settings])
        ///	declare @rowsChanged int = 0;
        ///	decla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateTeacherScript {
            get {
                return ResourceManager.GetString("UpdateTeacherScript", resourceCulture);
            }
        }
    }
}
