//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAC.RACModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetencyComment
    {
        public int Id { get; set; }
        public string Comment { get; set; }
        public int RACRequestCompetencyId { get; set; }
        public int UserId { get; set; }
        public int CandidateId { get; set; }
    
        public virtual RACRequestCompetency RACRequestCompetency { get; set; }
        public virtual Candidate Candidate { get; set; }
    }
}
