//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAC.RACModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RACRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RACRequest()
        {
            this.RACRequestCompetencies = new HashSet<RACRequestCompetency>();
            this.UploadedDocuments = new HashSet<UploadedDocument>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public int Status { get; set; }
        public bool IsGenEdOnly { get; set; }
        public int ProgramId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RACRequestCompetency> RACRequestCompetencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UploadedDocument> UploadedDocuments { get; set; }
        public virtual Program Program { get; set; }
        public virtual Candidate Candidate { get; set; }
    }
}
