//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAC.RACModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RACRequestCompetencyElement
    {
        public int Id { get; set; }
        public int Answer { get; set; }
        public int RACRequestCompetencyId { get; set; }
        public int CompetencyElementId { get; set; }
    
        public virtual RACRequestCompetency RACRequestCompetency { get; set; }
        public virtual CompetencyElement CompetencyElement { get; set; }
    }
}
